apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler 
metadata:
 name: rockstar-react 
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: rockstar-react-fe
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 5