apiVersion: apps/v1 
kind: Deployment
metadata:
  name: final-rockstar-app
spec:
  selector:
    matchLabels:
      app: final-rockstar-app
  replicas: 1
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      annotations:
        prometheus.io/path: "/status/format/prometheus"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        app: final-rockstar-app
    spec:
      containers:
        - image: cvam612/rockstar-front:minikube
          imagePullPolicy: Always
          name: final-rockstar-app
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: final-rockstar-app-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: final-rockstar-app