apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sa-flask-logic 
spec:
  selector:
    matchLabels:
      app: sa-flask-logic
  replicas: 2 
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: sa-flask-logic
    spec:
      containers:
        - image: cvam612/sa-flask-logic
          imagePullPolicy: Always
          name: sa-flask-logic
          ports:
            - containerPort: 5050